# Generated by Django 3.2.5 on 2021-07-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipomoneda',
            fields=[
                ('idmoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='id tipo moneda')),
                ('monedapago', models.CharField(max_length=20, verbose_name='moneda (peso o dolar)')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='numero de identificacion')),
                ('fotografia', models.ImageField(upload_to='')),
                ('nombreproveedor', models.CharField(max_length=50, verbose_name='nombre proveedor')),
                ('telefonoproveedor', models.IntegerField(verbose_name='telefono proveedor')),
                ('direccionproveedor', models.CharField(max_length=50, verbose_name='direccion proveedor')),
                ('emailproveedor', models.EmailField(max_length=40, verbose_name='email proveedor')),
                ('paisproveedor', models.CharField(max_length=30, verbose_name='pais proveedor')),
                ('passproveedor', models.CharField(max_length=15, verbose_name='pass proveedor')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomoneda')),
            ],
        ),
    ]
